package puter

import (
	"strconv"

	"orchids-api/internal/store"
)

var curatedPrimaryModelIDs = []string{
	"gpt-5.1",
	"gpt-5.1-codex",
	"gpt-5.1-codex-mini",
	"gpt-5.1-chat-latest",
	"gpt-5-2025-08-07",
	"gpt-5",
	"gpt-5-mini-2025-08-07",
	"gpt-5-mini",
	"gpt-5-nano-2025-08-07",
	"gpt-5-nano",
	"gpt-5-chat-latest",
	"gpt-4o",
	"gpt-4o-mini",
	"o1",
	"o1-mini",
	"o1-pro",
	"o3",
	"o3-mini",
	"o4-mini",
	"gpt-4.1",
	"gpt-4.1-mini",
	"gpt-4.1-nano",
	"gpt-4.5-preview",
	"claude-opus-4-5",
	"claude-opus-4-5-latest",
	"claude-opus-4.5",
	"claude-haiku-4-5-20251001",
	"claude-haiku-4.5",
	"claude-haiku-4-5",
	"claude-sonnet-4-5-20250929",
	"claude-sonnet-4.5",
	"claude-sonnet-4-5",
	"claude-opus-4-1-20250805",
	"claude-opus-4-1",
	"claude-opus-4-20250514",
	"claude-opus-4",
	"claude-opus-4-latest",
	"claude-sonnet-4-20250514",
	"claude-sonnet-4",
	"claude-sonnet-4-latest",
	"claude-3-7-sonnet-20250219",
	"claude-3-7-sonnet-latest",
	"claude-3-5-sonnet-20241022",
	"claude-3-5-sonnet-latest",
	"claude-3-5-sonnet-20240620",
	"claude-3-haiku-20240307",
	"mistral-large-latest",
	"mistral-medium-2508",
	"mistral-medium-latest",
	"mistral-medium",
	"ministral-3b-2410",
	"ministral-3b-latest",
	"ministral-8b-2410",
	"ministral-8b-latest",
	"open-mistral-7b",
	"mistral-tiny",
	"mistral-tiny-2312",
	"open-mistral-nemo",
	"open-mistral-nemo-2407",
	"mistral-tiny-2407",
	"mistral-tiny-latest",
	"pixtral-large-2411",
	"pixtral-large-latest",
	"mistral-large-pixtral-2411",
	"codestral-2508",
	"codestral-latest",
	"devstral-small-2507",
	"devstral-small-latest",
	"pixtral-12b-2409",
	"pixtral-12b",
	"pixtral-12b-latest",
	"mistral-small-2506",
	"mistral-small-latest",
	"magistral-medium-2509",
	"magistral-medium-latest",
	"magistral-small-2509",
	"magistral-small-latest",
	"mistral-moderation-2411",
	"mistral-moderation-latest",
	"mistral-ocr-2505",
	"mistral-ocr-latest",
	"grok-beta",
	"grok-vision-beta",
	"grok-3",
	"grok-3-fast",
	"grok-3-mini",
	"grok-3-mini-fast",
	"grok-2-vision",
	"grok-2",
	"deepseek-chat",
	"deepseek-reasoner",
	"gemini-1.5-flash",
	"gemini-2.0-flash",
	"gemini-2.0-flash-lite",
	"gemini-2.5-flash",
	"gemini-2.5-flash-lite",
	"gemini-2.5-pro",
	"gemini-3-pro-preview",
}

func SeedModels(baseID int) []store.Model {
	models := make([]store.Model, 0, len(curatedPrimaryModelIDs))
	for i, modelID := range curatedPrimaryModelIDs {
		models = append(models, store.Model{
			ID:        storeID(baseID + i),
			Channel:   "Puter",
			ModelID:   modelID,
			Name:      modelID,
			Status:    store.ModelStatusAvailable,
			IsDefault: modelID == "claude-opus-4-5",
			SortOrder: i,
		})
	}
	return models
}

func storeID(id int) string {
	return strconv.Itoa(id)
}
